### ISSUE TITLE
Typescript import broken for `fromFile`?

### ISSUE THREAD

**Issue by t3hmrman** [sindresorhus/hasha#18]
I just tried to use the typescript definitions and they're not working for me:

**`import hasha from "hasha"` -> the import works, but `hasha` is `undefined`**

**`import { hasha } from "hasha"` -> doesn't compile** (as expected, hasha is the default export, not one of many)

**`import * as hasha from "hasha"` -> works, but can't call `fromFile`** (`hasha` is the hashing function (so `input, options = {}) => ...`), but `fromFile` isn't a property of it for some reason)

You can reproduce this with a new project and the following commands:

```shell
$ yarn init 
$ yarn add hasha
$ yarn add @types/hasha
$ yarn add ts-node 
$ ./node_modules/.bin/ts-node -e 'import hasha from "hasha"; console.log("hasha?", hasha);' # first case (undefined)
$ ./node_modules/.bin/ts-node -e 'import {hasha} from "hasha"; console.log("hasha?", hasha);' # second case (type error)
$ ./node_modules/.bin/ts-node -e 'import * as hasha from "hasha"; console.log("hasha?", hasha.fromFile);' # third case (`hasha` itself is defined but `hasha.fromFile` is not)
```

Am I forgetting something fundamental about imports or is this a real bug? The first case `import hasha from "hasha"` should have been all I needed.

**Comment by dino-absoluto** [comment]
Cause by incorrect Typescript declaration file.

The code itself export hasha with
```javascript
module.exports = hasha;
```
Which is the NodeJS old style export
In Typescript it's supposed to be equivalent to
```typescript
export = hasha
```
But in `index.d.ts` it was defined ES Modules style as
```typescript
export default hasha
```

In ES Modules style:
`import hasha from "hasha"` is roughly equivalent to `const hasha = require("hasha").default`
Which is why you got undefined
`import * as hasha from "hasha"` => `const hasha = require("hasha")`
Which should works
But Typescript compiler see hasha as `{ default: hasha }` so it failed the type check.
The code itself will still run if you enable `--transpile-only` option (probably).
Or trick Typescript to ignore the error with `(hasha as any).fromFile()`

Also, when you import a CommonJS, use this:
```typescript
import hasha = require("hasha");
```

**Comment by sindresorhus** [comment]
Sorry, we had an incorrect TS definition. Should be fixed in v5.

https://github.com/sindresorhus/hasha/releases/tag/v5.0.0

**Comment by t3hmrman** [comment]
Hey thanks all for fixing this (and the rest of the library of course) — havent had time to get to a computer and respond

Cheers!
