### ISSUE TITLE
New version (5.1.0) throws webpack errors

### ISSUE THREAD

**Issue by oakromulo** [sindresorhus/hasha#25]
WARNING  Compiled with 1 warnings
warning  in ./node_modules/hasha/index.js

Critical dependency: the request of a dependency is an expression

**Comment by sindresorhus** [comment]
This is a Node.js module. There's no reason to use it with Webpack. Anyway, you can Google this error. It's a common Webpack problem.

**Comment by Livven** [comment]
> This is a Node.js module. There's no reason to use it with Webpack.

Disagree. Bundling a node app will generally yield significant size savings, partially due to tree shaking but also trivially due to throwing out all the other unnecessary files (READMEs, build outputs for different module systems, and so on).

See the fix in #26.

Thanks for all your work by the way!
